# Generated by Django 5.2.17 on 2026-09-30 21:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dependencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "formato_folio",
                    models.CharField(
                        help_text="# = un dígito, AAAA = año. Ejemplo: SSC-####/AAAA",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "rfc",
                    models.CharField(max_length=13, unique=True, verbose_name="RFC"),
                ),
            ],
            options={
                "verbose_name_plural": "proveedores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Requerimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.CharField(max_length=30, unique=True)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("autorizado", "Autorizado"),
                            ("pagado", "Pagado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField(default=datetime.date.today)),
                ("adjunto", models.FileField(blank=True, upload_to="adjuntos/%Y/")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                (
                    "dependencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requerimientos",
                        to="requerimientos.dependencia",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="requerimientos.proveedor",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "folio"],
            },
        ),
    ]
